# Generated by Django 5.0.6 on 2024-06-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='std_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='sub1_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='sub2_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='sub3_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='sub4_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='sub5_marks',
            field=models.FloatField(default=0),
        ),
    ]
